"""Generate appendix_c_model_index.md from assets/data/detectors.json (run from the repo root).

    python tools/build_model_index.py

The JSON file is the single source of truth for the Detection Atlas, this appendix and the
Chapter 34 figure. Edit the JSON, then re-run this script; never edit the appendix by hand.
"""

from __future__ import annotations

import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "assets" / "data" / "detectors.json"
OUT = ROOT / "appendix_c_model_index.md"

TIER_ORDER = ["mcu", "tiny", "edge", "realtime", "large", "open-vocab", "mllm", "classic"]
TIER_TITLE = {
    "mcu": "Microcontroller-class",
    "tiny": "Tiny (sub-2M parameters, mobile CPUs)",
    "edge": "Edge",
    "realtime": "Real-time (GPU-class)",
    "large": "Large / accuracy-first",
    "open-vocab": "Open-vocabulary",
    "mllm": "Multimodal LLM detectors",
    "classic": "Classic baselines",
}


def fmt(v, nd=1):
    if v is None or v == "":
        return "—"
    if isinstance(v, float):
        return f"{v:.{nd}f}".rstrip("0").rstrip(".") if nd else str(v)
    return str(v)


def nms_label(v):
    return {True: "needs NMS", False: "NMS-free", "opt": "optional"}.get(v, str(v))


def main():
    data = json.loads(DATA.read_text())
    models = data["models"]
    by_tier: OrderedDict[str, list] = OrderedDict((t, []) for t in TIER_ORDER)
    for m in models:
        by_tier.setdefault(m.get("tier", "other"), []).append(m)

    lines = [
        "---",
        'title: "Appendix C — Model Index"',
        "---",
        "",
        "[← Back to Table of Contents](./README.md)",
        "",
        "# Appendix C — Model Index",
        "",
        "> *Generated by `tools/build_model_index.py` from `assets/data/detectors.json`. Do not edit by hand.*",
        "",
        f"{len(models)} detectors. Every number is copied from the source named in the last column; nothing is",
        "re-measured. **AP** is COCO val2017 AP50:95 unless the note says otherwise. **Latency** is only comparable",
        "between rows with the same hardware string; rows marked *needs NMS* usually exclude NMS time. See",
        "[Chapter 34](./34_yolo_family_performance.md) for how to read these numbers and the",
        "[Detection Atlas](./atlas.md) for the interactive version.",
        "",
    ]
    for tier, rows in by_tier.items():
        if not rows:
            continue
        rows = sorted(rows, key=lambda r: (r.get("family", ""), r.get("year", 0), r.get("latency_ms") or 0, r.get("name", "")))
        lines += [
            "---",
            "",
            f"## {TIER_TITLE.get(tier, tier)}",
            "",
            "| Model | Family | Org | Year | Params (M) | GFLOPs | Input | COCO AP | Latency (ms) | Hardware | NMS | Pre-training | Licence | Source | Note |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
        ]
        for r in rows:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"**{r['name']}**",
                        fmt(r.get("family")),
                        fmt(r.get("org")),
                        fmt(r.get("year")),
                        fmt(r.get("params_m"), 2),
                        fmt(r.get("gflops"), 2),
                        fmt(r.get("input")),
                        fmt(r.get("coco_ap"), 2),
                        fmt(r.get("latency_ms"), 2),
                        fmt(r.get("latency_hw")),
                        nms_label(r.get("nms")),
                        fmt(r.get("pretrain")),
                        fmt(r.get("license")),
                        fmt(r.get("source")).replace("|", "/"),
                        fmt(r.get("note", "")).replace("|", "/") if r.get("note") else "",
                    ]
                )
                + " |"
            )
        lines.append("")
    meta = data.get("_meta", {})
    lines += [
        "---",
        "",
        "## Data rules",
        "",
        f"- {meta.get('description', '')}",
        f"- Latency rule: {meta.get('latency_rule', '')}",
        "",
        "**Back to:** [Table of Contents](./README.md) · [Detection Atlas](./atlas.md)",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(models)} models)")


if __name__ == "__main__":
    main()
